[package]
name = "typst-as-library-example"
version = "0.1.0"
edition = "2021"

[dependencies]
typst = "0.13.1"
typst-as-library = { path = "../.." }
typst-html = "= 0.13.1"
typst-pdf = "0.13"
typst-svg = "0.13.1"
